In [2]:
import pandas as pd

In [50]:
tabela_alvos_furto1 = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\Alvos - Furto - Jan 2022 a Mar 2025.csv',sep=';', encoding='latin1')
tabela_alvos_furto2 = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\Alvos - Furto - Jan 2018 a Dez 2021.csv',sep=';', encoding='latin1')
tabela_alvos_furto3 = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\Alvos - Furto - Jan 2022 a Mar 2025.csv',sep=';', encoding='latin1')

In [65]:
tabela_alvos_furtos = pd.concat([tabela_alvos_furto1, tabela_alvos_furto2, tabela_alvos_furto3], ignore_index=True)

In [66]:
tabela_alvos_furtos.shape

(2504500, 26)

In [67]:
tabela_alvos_furtos = tabela_alvos_furtos.loc[tabela_alvos_furtos['Município'] == 'JUIZ DE FORA',:]

In [68]:
tabela_alvos_furtos.shape

(66388, 26)

In [69]:
tabela_alvos_furtos.to_csv('dados/furtos.csv')

### Roubos

In [71]:
tabela_alvos_roubos = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Alvos - Roubo - Jan 2015 a Mar 2025.csv',sep=';', encoding='latin1')
tabela_alvos_roubos.shape

(618749, 26)

In [72]:
tabela_alvos_roubos = tabela_alvos_roubos.loc[tabela_alvos_roubos['Município'] == 'JUIZ DE FORA',:]

In [73]:
tabela_furtos_roubos = pd.concat([tabela_alvos_furtos, tabela_alvos_roubos], ignore_index=True)

In [74]:
tabela_furtos_roubos.shape

(76665, 26)

In [75]:
tabela_furtos_roubos.to_csv('dados/furtos_roubos.csv')

## Crimes violentos

In [76]:
tabela_crimes_violentos1 = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Crimes Violentos - Jan 2012 a Dez 2021.csv', sep = ';', encoding='latin1')
tabela_crimes_violentos2 = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Crimes Violentos - Jan 2022 a Mar 2025.csv', sep = ';',  encoding='latin1')

In [77]:
tabela_crimes_violentos = pd.concat([tabela_crimes_violentos1, tabela_crimes_violentos2], ignore_index=True)

In [78]:
tabela_crimes_violentos.shape

(1095920, 25)

In [79]:
tabela_crimes_violentos = tabela_crimes_violentos.loc[tabela_crimes_violentos['Município'] == 'JUIZ DE FORA',:]

In [86]:
tabela_crimes_violentos.to_csv('dados/crimes_violentos.csv')

## Lesão corporal

In [82]:
tabela_lesao_corporal = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Lesão Corporal - Jan 2012 a Mar 2025.csv', sep = ';', encoding = 'latin1')

C:\Users\Carlos\AppData\Local\Temp\ipykernel_19332\1859576687.py:1: DtypeWarning: Columns (0,2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,24) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela_lesao_corporal = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Lesão Corporal - Jan 2012 a Mar 2025.csv', sep = ';', encoding = 'latin1')

In [83]:
tabela_lesao_corporal.shape

(1048575, 25)

In [84]:
tabela_lesao_corporal = tabela_lesao_corporal.loc[tabela_lesao_corporal['Município'] == 'JUIZ DE FORA',:]

In [87]:
tabela_lesao_corporal.to_csv('dados/lesao_corporal.csv')

## Roubos / Furto Veículos

In [88]:
tabela_veiculos_furto = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Veiculos - Furto - Jan 2015 a Mar 2025.csv', sep = ';', encoding = 'latin1')
tabela_veiculos_roubo = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Veiculos - Roubo - Jan 2015 a Mar 2025.csv', sep = ';', encoding = 'latin1')

C:\Users\Carlos\AppData\Local\Temp\ipykernel_19332\4140296760.py:1: DtypeWarning: Columns (0,2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela_veiculos_furto = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Veiculos - Furto - Jan 2015 a Mar 2025.csv', sep = ';', encoding = 'latin1')
C:\Users\Carlos\AppData\Local\Temp\ipykernel_19332\4140296760.py:2: DtypeWarning: Columns (0,2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela_veiculos_roubo = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Veiculos - Roubo - Jan 2015 a Mar 2025.csv', sep = ';', encoding = 'latin1')

In [89]:
tabela_veiculos = pd.concat([tabela_veiculos_furto, tabela_veiculos_roubo], ignore_index=True)

In [90]:
tabela_veiculos.shape

(1736083, 28)

In [92]:
tabela_veiculos = tabela_veiculos.loc[tabela_veiculos['Município'] == 'JUIZ DE FORA',:]

In [93]:
tabela_veiculos.to_csv('dados/veiculos.csv')

### Vitimas_homicidio

In [24]:
tabela_vitimas_homicidio = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\arquivos_apoio\Vítimas de Homicidio Consumado - Jan 2012 a Mar 2025.csv', sep = ';', encoding ='latin1')

In [25]:
tabela_vitimas_homicidio.shape

(43492, 37)

In [26]:
tabela_vitimas_homicidio.columns

Index(['Número REDS', 'Qtd Envolvidos', 'Natureza Principal Final', 'Ano Fato',
       'Mês Fato Resumido', 'Mês Numérico Fato', 'Data Fato',
       'Dia da Semana Fato', 'Horário Fato', 'Faixa 1 Hora Fato',
       'Faixa 6 Horas Fato', 'Causa Presumida', 'Desc Longa Meio Utilizado',
       'Descrição Grupo Local Imediato', 'Descrição Local Imediato',
       'Logradouro Ocorrência - Tipo', 'Bairro - FATO',
       'Bairro Não Cadastrado - FATO', 'BAIRRO - FATO FINAL',
       'BAIRRO - FATO FINAL -Município', 'Município - FATO',
       'Município - Código - FATO', 'UF - Sigla - FATO',
       'Unid Registro Nível 9', 'RISP', 'RMBH',
       'Tipo_Envolvimento_Lesão_Final', 'Idade Aparente', 'Sexo', 'Cútis',
       'Escolaridade', 'Relação Vítima/Autor', 'Tipo Logradouro Envolvido',
       'Bairro Envolvido', 'Bairro Envolvido Não Cadastrado',
       'Município Envolvido', 'UF Envolvido - Nome'],
      dtype='object')

In [101]:
tabela_vitimas_homicidio = tabela_vitimas_homicidio.loc[tabela_vitimas_homicidio['Município - FATO'] == 'JUIZ DE FORA',:]

In [27]:
tabela_vitimas_homicidio.to_csv('dados/vitimas_homicidio.csv')

In [28]:
crimes_violencia = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\crimes_violentos.csv',sep = ',')
furtos_roubos = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\furtos_roubos.csv',sep = ',')
lesao_corporal = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\lesao_corporal.csv',sep = ',')
veiculos = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\veiculos.csv',sep = ',')
vitimas_homicidio = pd.read_csv(r'C:\projetos\analise-da-violencia-em-juiz-de-fora\dados\vitimas_homicidio.csv',sep = ',')

In [29]:
crimes_violencia

,Unnamed: 0,Número REDS,Qtde Ocorrências,Natureza Principal Completa,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,...,Logradouro Ocorrência - Tipo,Bairro,Bairro Não Cadastrado,Bairro - FATO FINAL,Bairro - FATO FINAL - Municipio,Município,Município - Código,UF - Sigla,RISP,RMBH
0,13,2012-000001066-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,03:05:00,...,AVENIDA,DISTRITO INDUSTRIAL,NaN,DISTRITO INDUSTRIAL,"DISTRITO INDUSTRIAL, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
1,117,2012-000013850-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,20:30:00,...,RUA,MUCUNGE DA GRAMA,NaN,MUCUNGE DA GRAMA,"MUCUNGE DA GRAMA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
2,190,2012-000008207-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,02/01/2012,SEGUNDA-FEIRA,13:00:00,...,AVENIDA,SAO BENEDITO,NaN,SAO BENEDITO,"SAO BENEDITO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
3,228,2012-000011492-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,02/01/2012,SEGUNDA-FEIRA,18:00:00,...,AVENIDA,MARIANO PROCOPIO,NaN,MARIANO PROCOPIO,"MARIANO PROCOPIO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
4,403,2012-000018063-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,03/01/2012,TERÇA-FEIRA,16:10:00,...,AVENIDA,CENTRO,NaN,CENTRO,"CENTRO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20747,1092074,2025-007569427-001,1.0,HOMICIDIO CONSUMADO,2025.0,FEV,2.0,17/02/2025,SEGUNDA-FEIRA,05:01:00,...,RUA,MUCUNGE DA GRAMA,NaN,MUCUNGE DA GRAMA,"MUCUNGE DA GRAMA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
20748,1092079,2025-005116426-001,1.0,HOMICIDIO CONSUMADO,2025.0,FEV,2.0,02/02/2025,DOMINGO,17:03:01,...,RUA,CENTRO,NaN,CENTRO,"CENTRO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
20749,1092085,2025-013469761-001,1.0,HOMICIDIO CONSUMADO,2025.0,MAR,3.0,23/03/2025,DOMINGO,00:44:10,...,RUA,AEROPORTO,NaN,AEROPORTO,"AEROPORTO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
20750,1092086,2025-010363017-001,1.0,HOMICIDIO CONSUMADO,2025.0,MAR,3.0,05/03/2025,QUARTA-FEIRA,01:47:46,...,RUA,JOQUEI CLUBE 2,NaN,JOQUEI CLUBE 2,"JOQUEI CLUBE 2, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
20751,1092090,2025-012285749-001,1.0,HOMICIDIO CONSUMADO,2025.0,MAR,3.0,16/03/2025,DOMINGO,07:31:59,...,ESTRADA,INVÁLIDO,VALE DOS PEOES,VALE DOS PEOES,"VALE DOS PEOES, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG

In [30]:
furtos_roubos.head()

,Unnamed: 0,Número REDS,Qtde Ocorrências,Natureza Principal Completa,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,...,Logradouro Ocorrência - Tipo,Bairro,Bairro Não Cadastrado,Bairro - FATO FINAL,Bairro - FATO FINAL - Municipio,Município,Município - Código,UF - Sigla,RISP,RMBH
0,0,2022-015861884-001,1,FURTO CONSUMADO,2022,ABR,4,12/04/2022,TERÇA-FEIRA,23:00:00,...,POVOADO,INVÁLIDO,NaN,DESCONHECIDO,"DESCONHECIDO, JUIZ DE FORA",JUIZ DE FORA,313670,MG,4,3) Interior de MG
1,1,2024-000802602-001,1,FURTO CONSUMADO,2024,JAN,1,06/01/2024,SÁBADO,10:32:41,...,RODOVIA,INVÁLIDO,NaN,DESCONHECIDO,"DESCONHECIDO, JUIZ DE FORA",JUIZ DE FORA,313670,MG,4,3) Interior de MG
2,2,2022-017075026-001,1,FURTO CONSUMADO,2022,ABR,4,22/04/2022,SEXTA-FEIRA,10:31:14,...,FAZENDA,INVÁLIDO,NaN,DESCONHECIDO,"DESCONHECIDO, JUIZ DE FORA",JUIZ DE FORA,313670,MG,4,3) Interior de MG
3,3,2023-022810939-001,1,FURTO CONSUMADO,2023,MAI,5,15/05/2023,SEGUNDA-FEIRA,10:50:22,...,FAZENDA,INVÁLIDO,NaN,DESCONHECIDO,"DESCONHECIDO, JUIZ DE FORA",JUIZ DE FORA,313670,MG,4,3) Interior de MG
4,4,2024-025167675-001,1,FURTO CONSUMADO,2024,JUN,6,03/06/2024,SEGUNDA-FEIRA,18:53:03,...,FAZENDA,INVÁLIDO,NaN,DESCONHECIDO,"DESCONHECIDO, JUIZ DE FORA",JUIZ DE FORA,313670,MG,4,3) Interior de MG

In [31]:
lesao_corporal.head()

,Unnamed: 0,Número REDS,Qtde Ocorrências,Natureza Principal Completa,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,...,Logradouro Ocorrência - Tipo,Bairro,Bairro Não Cadastrado,Bairro - FATO FINAL,Bairro - FATO FINAL - Municipio,Município,Município - Código,UF - Sigla,RISP,RMBH
0,70,2012-000000667-001,1.0,LESAO CORPORAL CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,01:00:00,...,RUA,VILA IDEAL,NaN,VILA IDEAL,"VILA IDEAL, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
1,203,2012-000001414-001,1.0,LESAO CORPORAL CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,04:30:00,...,RUA,VILA IDEAL,NaN,VILA IDEAL,"VILA IDEAL, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
2,204,2012-000001421-001,1.0,LESAO CORPORAL CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,03:50:00,...,AVENIDA,NOVA ERA,NaN,NOVA ERA,"NOVA ERA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
3,255,2012-000001806-001,1.0,LESAO CORPORAL CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,04:00:00,...,AVENIDA,MUCUNGE DA GRAMA,NaN,MUCUNGE DA GRAMA,"MUCUNGE DA GRAMA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
4,289,2012-000002200-001,1.0,LESAO CORPORAL CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,07:00:00,...,RUA,OLAVO COSTA,NaN,OLAVO COSTA,"OLAVO COSTA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG

In [32]:
veiculos.head()

,Unnamed: 0,Número REDS,Qtde Veículos,Natureza Principal Completa,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,...,Logradouro Ocorrência - Tipo,Bairro,Bairro Não Cadastrado,Bairro - FATO FINAL,Bairro - FATO FINAL - Municipio,Município,Município - Código,UF - Sigla,RISP,RMBH
0,93,2015-000079420-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,02/01/2015,SEXTA-FEIRA,00:30:00,...,RUA,FRANCISCO BERNARDINO,NaN,FRANCISCO BERNARDINO,"FRANCISCO BERNARDINO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
1,132,2015-000119317-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,02/01/2015,SEXTA-FEIRA,20:30:00,...,RUA,CIDADE DO SOL,NaN,CIDADE DO SOL,"CIDADE DO SOL, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
2,238,2015-000198015-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,04/01/2015,DOMINGO,10:00:00,...,AVENIDA,ALTO DOS PASSOS,NaN,ALTO DOS PASSOS,"ALTO DOS PASSOS, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
3,256,2015-000218977-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,04/01/2015,DOMINGO,16:00:00,...,RUA,QUINTA DAS AVENIDAS,QUINTA DAS AVENIDAS,QUINTA DAS AVENIDAS,"QUINTA DAS AVENIDAS, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
4,270,2015-000237512-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,04/01/2015,DOMINGO,22:30:00,...,RUA,GRAJAU,NaN,GRAJAU,"GRAJAU, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG

In [33]:
vitimas_homicidio.head()

,Unnamed: 0,Número REDS,Qtd Envolvidos,Natureza Principal Final,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,...,Idade Aparente,Sexo,Cútis,Escolaridade,Relação Vítima/Autor,Tipo Logradouro Envolvido,Bairro Envolvido,Bairro Envolvido Não Cadastrado,Município Envolvido,UF Envolvido - Nome
0,0,2023-054904608-001,1,HOMICIDIO CONSUMADO,2023,NOV,11,24/11/2023,SEXTA-FEIRA,19:40:00,...,54,MASCULINO,BRANCA,ENSINO FUNDAMENTAL INCOMPLETO (8 ANOS ESTUDO),AMIGO / CONHECIDO,PROPRIEDADE,NAO INFORMADO,NaN,ITAPEVA,MINAS GERAIS
1,1,2023-054979574-001,1,HOMICIDIO CONSUMADO,2023,NOV,11,25/11/2023,SÁBADO,11:53:49,...,41,MASCULINO,PARDA,ESCOLARIDADE - IGNORADA,IGNORADA,NAO INFORMADO,NAO INFORMADO,NaN,SEM INFORMAÇÃO,PREENCHIMENTO OPCIONAL
2,2,2023-055706458-001,1,HOMICIDIO CONSUMADO,2023,NOV,11,29/11/2023,QUARTA-FEIRA,20:38:37,...,41,MASCULINO,BRANCA,ALFABETIZADO,SEM RELACIONAMENTO,RUA,PONTE SEGURA,NaN,SENADOR AMARAL,MINAS GERAIS
3,3,2023-053136570-001,1,HOMICIDIO CONSUMADO,2023,NOV,11,14/11/2023,TERÇA-FEIRA,07:10:00,...,66,MASCULINO,BRANCA,ENSINO MEDIO COMPLETO (2º GRAU),SEM RELACIONAMENTO,RUA,SANTA ROSA,NaN,ITAJUBA,MINAS GERAIS
4,4,2023-053997278-001,1,HOMICIDIO CONSUMADO,2023,NOV,11,19/11/2023,DOMINGO,19:16:09,...,30,FEMININO,BRANCA,ESCOLARIDADE - IGNORADA,CONJUGE / COMPANHEIRO,RUA,BOA VISTA,NaN,ITAJUBA,MINAS GERAIS

In [34]:
df_crimes = pd.concat([crimes_violencia, furtos_roubos, lesao_corporal,veiculos,vitimas_homicidio], ignore_index=True)

In [36]:
df_crimes.to_csv('dados\crimesjf.csv')

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Carlos\AppData\Local\Temp\ipykernel_8472\975107113.py:1: SyntaxWarning: invalid escape sequence '\c'
  df_crimes.to_csv('dados\crimesjf.csv')